#%RAML 1.0 Trait
usage: Use this header to pass user ID that genareted this flow, for end-to-end traceability of the operation/transaction. 
headers:  
  client_id:
    type: string
    required: true
  client_secret:
    type: string
    required: true
responses:
  401:
    description: Unauthorized or invalid client application credentials
  500:
    description: Bad response from authorization server, or WSDL SOAP Fault error