#%RAML 1.0 Trait
description: HTTP Headers for the Rest APIs.
headers:
  Content-Type: 
    description: 
    required: true
    type: string 
    enum:
      - application/json
      - application/xml
